### ISSUE TITLE
Banana

### ISSUE THREAD

**Issue by pendragons-code** [DiffuseHyperion/ePortfolio#1]
I tot need to use sites.google.com? I had to redo my entire site with google sites for me e-portfolio with that. As much as I hate that, you should not waste your time here. Rather you should compile your achievements and put it on a timeline.

**Comment by pendragons-code** [comment]
Also, most importantly, remember to get a lists of duties you were present for and send that in as duties act as evidence of you achievements.

**Comment by DiffuseHyperion** [comment]
sure, will start doing that
